account_bundle:
    resource:
        path: ../src/AccountBundle/Application/Controller/
        namespace: App\AccountBundle\Application\Controller
    type: attribute
    prefix: /api/v1/account
    name_prefix: account_