nelmio_api_doc:
    documentation:
        info:
            title: PostY API
            description: API Documentation
            version: 1.0.0
    areas:
        default:
            path_patterns:
                - ^/api/v1
        account:
            path_patterns:
                - ^/api/v1/account
            documentation:
                info:
                    title: Account API
                    description: API for managing accounts
        post:
            path_patterns:
                - ^/api/v1/post
            documentation:
                info:
                    title: Post API
                    description: API for managing posts
